name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies via Makefile
        run: make install

      - name: Lint & run tests
        run: make check

      - name: Run test coverage
        run: make test-coverage

      - name: Verify coverage report
        run: |
          ls -la coverage.xml
          [[ -s coverage.xml ]] && echo "coverage.xml OK" || (echo "coverage.xml missing or empty" && exit 1)

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=lyovaparsyan94_python-project-50
            -Dsonar.organization=lyovaparsyan94
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**
