name: Build & Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests & generate coverage report
        run: |
          pytest --cov=gendiff --cov-report=xml:coverage.xml

      - name: Verify coverage report
        run: |
          ls -la
          [[ -s coverage.xml ]] && echo "coverage.xml OK" || (echo "coverage.xml missing or empty" && exit 1)

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=lyovaparsyan94_python-project-50
            -Dsonar.organization=lyovaparsyan94
            -Dsonar.python.coverage.reportPaths=coverage.xml
